"""Codex adapter — runs jobs through the official openai-codex App Server SDK.

Migrated from the legacy `openai-codex-sdk` (which wrapped `codex exec` over a
one-way stdout stream) to `openai-codex`, the App Server JSON-RPC SDK
(`AsyncCodex` → threads → turns → notifications). The move buys three things
the old wrapper could not offer (issue #38): subscription-backed auth via
ChatGPT login, and — for the follow-up leash layer — a bidirectional,
host-answerable command-approval channel (`approval_handler`).

The base-tier contract is unchanged: this adapter still yields NORMALIZED
event payload dicts (`thread.started`, `turn.completed`, `turn.failed`,
`item.completed`) and the base class owns everything else. `_normalize_notification`
maps the SDK's typed notifications onto those payloads and passes plain dicts
through untouched, so tests drive the state machine with normalized dicts (as
before) without importing the SDK.

Auth: the App Server uses Codex's own credential store under CODEX_HOME. The
deployment either mounts existing ChatGPT credentials there (subscription
path) or sets CODEX_API_KEY/OPENAI_API_KEY (logged in per session). MCP
servers are still declared via config.toml in CODEX_HOME, written at startup.
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Any, AsyncIterator, Callable

from miragen.executor.base import ExecutorBackend
from miragen.models import AgentProfile

logger = logging.getLogger("miragen.executor")

# miragen's sandbox_mode strings → the SDK's Sandbox enum values. Not a direct
# construction: the SDK spells full access "full-access", miragen "danger-full-access".
_SANDBOX_VALUES = {
    "read-only": "read-only",
    "workspace-write": "workspace-write",
    "danger-full-access": "full-access",
}

# miragen approval_policy → the SDK's coarse ApprovalMode. 'never' (the
# unattended default) maps to deny_all, which sets AskForApproval=never: Codex
# runs within the sandbox without pausing to ask — today's behavior exactly.
# Everything else asks and is auto-reviewed. The custom per-command gate
# (issue #38 Phase 2) rides `approval_handler`, a separate seam.
_APPROVAL_MODES = {
    "never": "deny_all",
    "on-request": "auto_review",
    "on-failure": "auto_review",
    "untrusted": "auto_review",
}

# item.completed item types that carry the agent's final message text.
_MESSAGE_ITEM_TYPES = {"agentMessage", "agent_message"}


class CodexExecutor(ExecutorBackend):
    """Runs jobs through the openai-codex App Server SDK (`pip install miragen[codex]`).

    `session_factory` is the test seam: it receives
    `(prompt, *, thread_id, first_turn, options)` and returns an async iterator
    of notifications — SDK objects in production, or plain normalized payload
    dicts in tests (which pass straight through `_normalize_notification`).
    """

    def __init__(
        self,
        profile: AgentProfile,
        *,
        runs_root: Path = Path("/agent/runs"),
        session_factory: Callable[..., AsyncIterator[Any]] | None = None,
    ):
        super().__init__(profile, runs_root=runs_root)
        self._session_factory = session_factory or self._default_session

    # ── Startup ────────────────────────────────────────────────────────────

    def prepare(self) -> None:
        """Write the executor's MCP/config into CODEX_HOME (idempotent, once at
        startup). The App Server reads CODEX_HOME's config.toml and credential
        store; auth is provisioned by the deployment (mounted ChatGPT creds or
        CODEX_API_KEY), never profile content."""
        codex_home = Path(self.spec.codex_home)
        codex_home.mkdir(parents=True, exist_ok=True)
        os.environ.setdefault("CODEX_HOME", str(codex_home))

        config_path = codex_home / "config.toml"
        config_path.write_text(self._render_config())
        logger.info(f"[{self.profile.name}] executor config written: {config_path}")

        has_creds = (codex_home / "auth.json").exists()
        has_key = bool(os.environ.get("CODEX_API_KEY") or os.environ.get("OPENAI_API_KEY"))
        if not has_creds and not has_key:
            logger.warning(
                f"[{self.profile.name}] no credentials in {codex_home} and no "
                "CODEX_API_KEY/OPENAI_API_KEY — executor turns will fail auth. Mount "
                "ChatGPT credentials into CODEX_HOME (subscription) or set an API key."
            )

    def _render_config(self) -> str:
        lines = [
            "# Generated by miragen at startup — do not edit; edit the agent profile instead.",
            f"# agent: {self.profile.name}",
        ]
        for server in self.spec.mcp_servers or []:
            lines += ["", f"[mcp_servers.{server.name}]", f'url = "{server.url}"']
            if server.bearer_token_env:
                lines.append(f'bearer_token_env_var = "{server.bearer_token_env}"')
        return "\n".join(lines) + "\n"

    # ── Turn streaming ─────────────────────────────────────────────────────

    async def _stream_turn(
        self,
        prompt: str,
        *,
        run_id: str,
        thread_id: str | None,
        workspace: Path,
        first_turn: bool,
    ) -> AsyncIterator[dict[str, Any]]:
        session = self._session_factory(
            prompt,
            thread_id=thread_id,
            first_turn=first_turn,
            options=self._options(workspace),
        )
        async for note in session:
            for payload in _normalize_notification(note):
                yield payload

    def _options(self, workspace: Path) -> dict[str, Any]:
        """Backend-agnostic turn options, resolved from the profile. Kept as a
        dict so the test seam sees the same inputs the SDK path does."""
        return {
            "cwd": str(workspace),
            "sandbox": _SANDBOX_VALUES[self.spec.sandbox_mode],
            "approval_mode": _APPROVAL_MODES[self.spec.approval_policy],
            "model": self.spec.model,
            "reasoning_effort": self.spec.reasoning_effort,
            "network_access": self.spec.network_access,
            "web_search": self.spec.web_search,
        }

    # ── Real SDK session (default seam) ──────────────────────────────────────

    async def _default_session(
        self,
        prompt: str,
        *,
        thread_id: str | None,
        first_turn: bool,
        options: dict[str, Any],
    ) -> AsyncIterator[Any]:
        """Drive one turn through the App Server SDK, yielding a synthetic
        thread.started dict followed by the turn's raw notifications."""
        from openai_codex import AsyncCodex, ApprovalMode, CodexConfig, ReasoningEffort, Sandbox

        config = CodexConfig(config_overrides=_config_overrides(options))
        async with AsyncCodex(config) as codex:
            await self._login(codex)
            sandbox = Sandbox(options["sandbox"])
            approval = ApprovalMode(options["approval_mode"])
            if thread_id:
                thread = await codex.thread_resume(
                    thread_id, approval_mode=approval, cwd=options["cwd"],
                    model=options["model"], sandbox=sandbox,
                )
            else:
                thread = await codex.thread_start(
                    approval_mode=approval, cwd=options["cwd"],
                    model=options["model"], sandbox=sandbox,
                )
            # thread.id is the resume handle; emit it before streaming so a
            # cancelled (timed-out) turn still recovers it (same reasoning as
            # the legacy adapter).
            yield {"type": "thread.started", "thread_id": thread.id}

            effort = ReasoningEffort(options["reasoning_effort"]) if options["reasoning_effort"] else None
            turn = await thread.turn(prompt, effort=effort)
            stream = turn.stream()
            try:
                async for note in stream:
                    yield note
            finally:
                await stream.aclose()

    async def _login(self, codex: Any) -> None:
        """Log in with an API key when one is configured; otherwise rely on the
        mounted ChatGPT credential store (the subscription path)."""
        key = os.environ.get("CODEX_API_KEY") or os.environ.get("OPENAI_API_KEY")
        if key:
            await codex.login_api_key(key)


def _config_overrides(options: dict[str, Any]) -> tuple[str, ...]:
    """`-c key=value` app-server overrides for knobs the high-level thread API
    doesn't expose directly (network access, web search)."""
    overrides: list[str] = []
    if options.get("network_access"):
        overrides.append("sandbox_workspace_write.network_access=true")
    if options.get("web_search"):
        overrides.append("features.web_search_request=true")
    return tuple(overrides)


# ── Notification normalization ───────────────────────────────────────────────

def _normalize_notification(note: Any) -> list[dict[str, Any]]:
    """Map one SDK notification onto zero or more normalized base-tier payloads.

    Matches on class name (not isinstance) so tests can drive it with plain
    stand-in classes, and passes plain dicts straight through so the state
    machine can be tested with normalized payloads directly — the same seam
    the Claude Code adapter uses.
    """
    if isinstance(note, dict):  # test seam / synthetic thread.started
        return [note]

    payload = getattr(note, "payload", note)
    name = type(payload).__name__

    if name == "ItemCompletedNotification":
        return _normalize_item(getattr(payload, "item", None))

    if name == "TurnCompletedNotification":
        turn = getattr(payload, "turn", None)
        status = _enum_value(getattr(turn, "status", None))
        if status == "failed":
            error = getattr(turn, "error", None)
            message = getattr(error, "message", None) or "turn failed"
            return [{"type": "turn.failed", "error": {"message": message}}]
        return [{"type": "turn.completed", "usage": _usage_from_turn(turn)}]

    if name == "ThreadTokenUsageUpdatedNotification":
        # Usage is folded into the turn.completed payload; the interim
        # updates need no separate normalized event.
        return []

    return []  # TurnStarted, reasoning deltas, and anything unrecognized


def _normalize_item(item: Any) -> list[dict[str, Any]]:
    if item is None:
        return []
    thread_item = getattr(item, "root", item)  # ThreadItem is a RootModel union
    item_type = _enum_value(getattr(thread_item, "type", None))

    if item_type in _MESSAGE_ITEM_TYPES:
        return [{
            "type": "item.completed",
            "item": {"type": "agent_message", "text": getattr(thread_item, "text", "") or ""},
        }]

    # Everything else (commandExecution, fileChange, mcpToolCall, reasoning,
    # webSearch, …) is a tool/work item. Preserve the type and the command +
    # exit_code / status so the base tier's tool-call telemetry and the future
    # approval gate have what they need.
    normalized: dict[str, Any] = {"type": _snake(item_type)}
    for attr in ("command", "status", "exit_code"):
        value = getattr(thread_item, attr, None)
        if value is not None:
            normalized[attr] = _enum_value(value)
    return [{"type": "item.completed", "item": normalized}]


def _usage_from_turn(turn: Any) -> dict[str, Any] | None:
    usage = getattr(turn, "usage", None)
    breakdown = getattr(usage, "last", None) if usage is not None else None
    if breakdown is None:
        return None
    return {
        "input_tokens": getattr(breakdown, "input_tokens", None),
        "output_tokens": getattr(breakdown, "output_tokens", None),
        "cached_input_tokens": getattr(breakdown, "cached_input_tokens", None),
    }


def _enum_value(value: Any) -> Any:
    """Unwrap str-Enum members (SDK types) to their string value; pass other
    values through."""
    return getattr(value, "value", value)


def _snake(camel: Any) -> str:
    """commandExecution → command_execution, so item types match the names the
    base tier and tests already use."""
    if not isinstance(camel, str):
        return str(camel)
    out = []
    for ch in camel:
        if ch.isupper():
            out.append("_")
            out.append(ch.lower())
        else:
            out.append(ch)
    return "".join(out)
