"""Codex adapter — runs jobs through the official openai-codex-sdk."""

from __future__ import annotations

import asyncio
import logging
import os
from pathlib import Path
from typing import Any, AsyncIterator, Callable

from miragen.executor.base import ExecutorBackend, event_payload
from miragen.models import AgentProfile

logger = logging.getLogger("miragen.executor")


class CodexExecutor(ExecutorBackend):
    """Runs jobs through the official openai-codex-sdk.

    The SDK wraps the bundled `codex` CLI (`codex exec --experimental-json`,
    `... resume <thread_id>`) and yields typed Pydantic events — verified
    against openai-codex-sdk 0.1.11. `thread_factory` exists for tests: it
    receives (thread_id | None, options) and returns a Thread-compatible
    object with `.id` and `.run_streamed(prompt)`.
    """

    def __init__(
        self,
        profile: AgentProfile,
        *,
        runs_root: Path = Path("/agent/runs"),
        thread_factory: Callable[..., Any] | None = None,
    ):
        super().__init__(profile, runs_root=runs_root)
        self._thread_factory = thread_factory or self._sdk_thread

    # ── Startup ────────────────────────────────────────────────────────────

    def prepare(self) -> None:
        """Write the executor's config (MCP servers, trust settings) into
        CODEX_HOME. Idempotent; called once at container startup.

        auth.json is NOT written here — it must be volume-mounted into
        CODEX_HOME by the deployment (per-agent Origo/Codex credentials are
        spawn-time secrets, never profile content).
        """
        codex_home = Path(self.spec.codex_home)
        codex_home.mkdir(parents=True, exist_ok=True)
        os.environ.setdefault("CODEX_HOME", str(codex_home))

        config_path = codex_home / "config.toml"
        config_path.write_text(self._render_config())
        logger.info(f"[{self.profile.name}] executor config written: {config_path}")

        if not (codex_home / "auth.json").exists() and not os.environ.get("CODEX_API_KEY"):
            logger.warning(
                f"[{self.profile.name}] no auth.json in {codex_home} and CODEX_API_KEY unset — "
                "executor spawns will fail auth. Mount auth.json into CODEX_HOME."
            )

    def _render_config(self) -> str:
        lines = [
            "# Generated by miragen at startup — do not edit; edit the agent profile instead.",
            f'# agent: {self.profile.name}',
        ]
        for server in self.spec.mcp_servers or []:
            lines += [
                "",
                f"[mcp_servers.{server.name}]",
                f'url = "{server.url}"',
            ]
            if server.bearer_token_env:
                # Reference by NAME: the per-agent credential is injected into the
                # container environment at spawn, not stored in config.
                lines.append(f'bearer_token_env_var = "{server.bearer_token_env}"')
        return "\n".join(lines) + "\n"

    # ── Turn streaming ─────────────────────────────────────────────────────

    async def _stream_turn(
        self,
        prompt: str,
        *,
        run_id: str,
        thread_id: str | None,
        workspace: Path,
        first_turn: bool,
    ) -> AsyncIterator[dict[str, Any]]:
        thread = self._thread_factory(
            thread_id=thread_id,
            options=self._thread_options(workspace),
        )
        # Some SDK paths only expose the id on the thread object. Persist it
        # BEFORE streaming when it's already known: a turn that hangs and gets
        # cancelled (turn_timeout_s) never reaches any post-stream code, and a
        # resume handle that only exists after the stream ends is a resume
        # handle the timeout path can't recover. Duplicate thread.started
        # events are harmless — the parser just re-records the same id.
        emitted_early = getattr(thread, "id", None)
        if emitted_early:
            yield {"type": "thread.started", "thread_id": emitted_early, "synthetic": True}
        streamed = await thread.run_streamed(prompt)
        saw_thread_started = False
        async for event in self._iter_events(streamed):
            payload = event_payload(event)
            if payload.get("type") == "thread.started":
                saw_thread_started = True
            yield payload
        if not saw_thread_started and not emitted_early and getattr(thread, "id", None):
            # Fallback for SDK paths where the id appears only after streaming.
            yield {"type": "thread.started", "thread_id": thread.id, "synthetic": True}

    # ── Pieces ─────────────────────────────────────────────────────────────

    def _sdk_thread(self, *, thread_id: str | None, options: Any):
        from openai_codex_sdk import Codex

        codex = Codex()
        if thread_id:
            return codex.resume_thread(thread_id, options)
        return codex.start_thread(options)

    def _thread_options(self, workspace: Path) -> Any:
        try:
            from openai_codex_sdk.types import ThreadOptions
        except ImportError:  # tests with a stub factory never reach the SDK
            return {
                "working_directory": str(workspace),
                "sandbox_mode": self.spec.sandbox_mode,
                "approval_policy": self.spec.approval_policy,
            }
        return ThreadOptions(
            model=self.spec.model,
            sandbox_mode=self.spec.sandbox_mode,
            working_directory=str(workspace),
            skip_git_repo_check=True,  # miragen initializes the repo itself
            model_reasoning_effort=self.spec.reasoning_effort,
            network_access_enabled=self.spec.network_access,
            web_search_enabled=self.spec.web_search,
            # Explicit ALWAYS: an unattended executor waiting on interactive
            # approval stalls the job (operational gotcha, miradb #293).
            approval_policy=self.spec.approval_policy,
        )

    @staticmethod
    async def _iter_events(streamed: Any) -> AsyncIterator[Any]:
        events = getattr(streamed, "events", streamed)
        if hasattr(events, "__aiter__"):
            async for event in events:
                yield event
        else:  # pragma: no cover — sync iterable stubs
            for event in events:
                yield event
                await asyncio.sleep(0)
