"""Hermetic GROK_HOME for the grok-build headless executor.

`grok_hermetic: true` makes miragen the owner of two files in the agent's
GROK_HOME, rewritten atomically at every start:

- ``config.toml`` — settings: compat discovery off, subagents / memory /
  managed MCPs / remote managed config / the shared leader / trace upload
  off, and the spec's ``mcp_servers`` as the only ``[mcp_servers.*]``
  (``Authorization = "Bearer ${ENV}"`` — grok expands the reference at load
  time, the secret itself never lands on disk).
- ``requirements.toml`` — the same switches as grok *policy* (keys marked
  ``pin`` there hold against GROK_* env and CLI flags), plus an exact-URL
  MCP allowlist with ``allow_managed_mcp_servers_only`` (drops servers from
  a workspace ``.mcp.json`` / ``.grok/config.toml`` and plugins) and
  ``allow_managed_hooks_only``.

Why both, and why an isolated HOME too (checked with ``grok inspect`` on
grok 1.0.41): the compat cells alone still load Claude *plugins* from
``~/.claude/plugins`` (skills, command hooks, stdio MCP servers) and
``~/.agents/skills``; policy keys in ``config.toml`` are ignored — only
``requirements.toml`` enforces the MCP allowlist. The executor therefore
also launches grok with ``HOME`` = ``<grok_home>/hermetic-home`` (empty).

Every other file in GROK_HOME (auth.json, sessions/, logs/) is left alone.
Ownership is a marker file, not a TOML comment, because grok itself
rewrites ``config.toml`` (e.g. it appends ``[marketplace]`` state).
"""

from __future__ import annotations

import contextlib
import json
import os
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from miragen.models import ExecutorSpec

OWNER_MARKER = ".miragen-hermetic-owner"
HERMETIC_HOME = "hermetic-home"
PRE_HERMETIC_BACKUP = "config.toml.pre-hermetic"

_COMPAT_CELLS = {
    # Every cell grok 1.0.41 documents (05-configuration.md "Harness
    # compatibility" + 26-config-reference.md `compat`).
    "claude": ("skills", "rules", "agents", "mcps", "hooks", "sessions"),
    "cursor": ("skills", "rules", "agents", "mcps", "hooks", "sessions"),
    "codex": ("skills", "hooks", "sessions"),
}


class HermeticHomeError(RuntimeError):
    """GROK_HOME is not safe to take over (another owner, foreign policy)."""


def hermetic_home_dir(grok_home: Path) -> Path:
    return grok_home / HERMETIC_HOME


def hermetic_owner(grok_home: Path) -> str | None:
    try:
        return (grok_home / OWNER_MARKER).read_text().strip() or None
    except FileNotFoundError:
        return None


def _q(value: str) -> str:
    """A TOML basic string (JSON escapes are a valid subset)."""
    return json.dumps(value)


def _settings(spec: "ExecutorSpec") -> list[str]:
    """Settings shared by config.toml and requirements.toml."""
    web = bool(spec.web_search)
    lines = [
        "[cli]",
        "auto_update = false",
        "use_leader = false",
        "",
        "[features]",
        "managed_config = false",
        f"backend_tools = {str(web).lower()}",
        "web_fetch = false",
        "",
        "[subagents]",
        "enabled = false",
        "",
        "[memory]",
        "enabled = false",
        "",
        "[memory_v2]",
        "enabled = false",
        "",
        "[managed_mcps]",
        "enabled = false",
        "",
        "[telemetry]",
        "trace_upload = false",
    ]
    for vendor, cells in _COMPAT_CELLS.items():
        lines += ["", f"[compat.{vendor}]"] + [f"{cell} = false" for cell in cells]
    return lines


def render_config(agent: str, spec: "ExecutorSpec") -> str:
    lines = [
        "# Generated by miragen (grok_hermetic) at every start — edits are",
        "# overwritten; change the agent profile instead.",
        f"# agent: {agent}",
        f"disable_web_search = {str(not spec.web_search).lower()}",
        "",
        *_settings(spec),
    ]
    for server in spec.mcp_servers or []:
        lines += ["", f"[mcp_servers.{server.name}]", f"url = {_q(server.url)}"]
        if server.bearer_token_env:
            header = "Bearer ${" + server.bearer_token_env + "}"
            lines.append(f"headers = {{ Authorization = {_q(header)} }}")
    return "\n".join(lines) + "\n"


def render_requirements(agent: str, spec: "ExecutorSpec") -> str:
    lines = [
        "# Generated by miragen (grok_hermetic) at every start — policy layer.",
        f"# agent: {agent}",
        "allow_managed_mcp_servers_only = true",
        "enable_all_project_mcp_servers = false",
        "allow_managed_hooks_only = true",
        "",
        *_settings(spec),
    ]
    # Exact URL (a pattern with a path matches only that path). With
    # allow_managed_mcp_servers_only, an empty list blocks every server.
    for server in spec.mcp_servers or []:
        lines += ["", "[[allowed_mcp_servers]]", f"server_url = {_q(server.url)}"]
    return "\n".join(lines) + "\n"


def _atomic_write(path: Path, text: str) -> None:
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(text)
            f.flush()
            os.fsync(f.fileno())
        os.chmod(tmp, 0o644)
        os.replace(tmp, path)
    except BaseException:
        with contextlib.suppress(OSError):
            os.unlink(tmp)
        raise


def write_hermetic_home(grok_home: Path, agent: str, spec: "ExecutorSpec") -> None:
    """Take over (or refresh) GROK_HOME's config for `agent`.

    Refuses a home another agent owns, and a requirements.toml miragen did
    not write (it may be an organisation's synced policy). A pre-existing
    unowned config.toml is kept once as config.toml.pre-hermetic.
    """
    grok_home.mkdir(parents=True, exist_ok=True)
    owner = hermetic_owner(grok_home)
    if owner is not None and owner != agent:
        raise HermeticHomeError(
            f"{grok_home} is the hermetic GROK_HOME of agent {owner!r}; "
            f"agent {agent!r} needs its own grok_home"
        )
    config = grok_home / "config.toml"
    requirements = grok_home / "requirements.toml"
    if owner is None:
        if requirements.exists():
            raise HermeticHomeError(
                f"{requirements} exists and was not written by miragen — refusing "
                "to replace a policy file (remove it or use another grok_home)"
            )
        if config.exists() and not (grok_home / PRE_HERMETIC_BACKUP).exists():
            os.replace(config, grok_home / PRE_HERMETIC_BACKUP)
        _atomic_write(grok_home / OWNER_MARKER, agent + "\n")

    _atomic_write(config, render_config(agent, spec))
    _atomic_write(requirements, render_requirements(agent, spec))
    home = hermetic_home_dir(grok_home)
    home.mkdir(mode=0o700, exist_ok=True)


def release_hermetic_home(grok_home: Path) -> None:
    """Undo write_hermetic_home (grok_hermetic turned off): drop the policy
    file and marker, restore the pre-hermetic config.toml if one was kept."""
    for name in ("requirements.toml", "config.toml", OWNER_MARKER):
        with contextlib.suppress(FileNotFoundError):
            (grok_home / name).unlink()
    backup = grok_home / PRE_HERMETIC_BACKUP
    if backup.exists():
        os.replace(backup, grok_home / "config.toml")
