"""Grok Build adapter — Phase A headless CLI (streaming-json).

Self-harnessed coding agent via the `grok` binary. No first-party agent SDK;
this adapter shells headless mode and normalizes NDJSON events onto the shared
executor contract. ACP + optional MIT client package are Phase B (later).

Auth (subscription-first, see docs/design/subscription-homes.md):
  - Primary: SuperGrok / X Premium+ OAuth under GROK_HOME (profile grok_home),
    populated once by `miragen grok-login` (`grok login --device-auth`).
  - Fallback: XAI_API_KEY (metered).
Agent containers never log in; they mount the shared home.

Session / resume:
  - First turn mints a UUID and passes `-s <uuid>` (new session only).
  - Resume passes `-r <uuid>`.
  thread.started is emitted with that id before the process streams, so a
  timed-out turn still recovers a resume handle.

Leash: Phase A uses `--always-approve` when unattended. Host leash has no
pre-tool seam on headless streaming-json — if leash is configured, the turn
fails loud rather than pretending the gate works (ACP later).
"""

from __future__ import annotations

import asyncio
import contextlib
import json
import logging
import os
import shutil
import signal
import uuid
from pathlib import Path
from typing import Any, AsyncIterator, Callable

from miragen.executor.base import ExecutorBackend
from miragen.models import AgentProfile

logger = logging.getLogger("miragen.executor")

_ERROR_TAIL_LINES = 20
_API_KEY_ENVS = ("XAI_API_KEY", "GROK_CODE_XAI_API_KEY")


class GrokBuildExecutor(ExecutorBackend):
    """Runs jobs through the Grok Build CLI headless mode.

    `session_factory` is the test seam: `(prompt, *, thread_id, first_turn,
    options) -> AsyncIterator` of already-normalized payload dicts, or of
    plain NDJSON event dicts (with a `type` field from the CLI) which are
    passed through `_normalize_event`.
    """

    def __init__(
        self,
        profile: AgentProfile,
        *,
        runs_root: Path = Path("/agent/runs"),
        session_factory: Callable[..., AsyncIterator[Any]] | None = None,
        grok_bin: str | None = None,
    ):
        super().__init__(profile, runs_root=runs_root)
        self._session_factory = session_factory or self._default_session
        self._grok_bin = grok_bin

    # ── Startup ────────────────────────────────────────────────────────────

    def prepare(self) -> None:
        home = Path(self.spec.grok_home)
        home.mkdir(parents=True, exist_ok=True)
        # Profile home wins over inherited GROK_HOME (same as kimi_home fix).
        os.environ["GROK_HOME"] = str(home)

        # Persist no-auto-update for headless fleets (also passed per-turn).
        config_path = home / "config.toml"
        if not config_path.exists():
            config_path.write_text(
                "# Generated by miragen at startup — edit the agent profile instead.\n"
                f"# agent: {self.profile.name}\n"
                "[cli]\n"
                "auto_update = false\n"
            )

        if self.spec.mcp_servers:
            logger.warning(
                f"[{self.profile.name}] grok-build Phase A cannot inject "
                "`mcp_servers` into the CLI — configure MCP under GROK_HOME "
                "or the project `.grok/` tree instead"
            )

        if self.leash_enabled:
            logger.warning(
                f"[{self.profile.name}] host leash is configured but grok-build "
                "Phase A (headless) has no pre-tool approval seam — turns will "
                "fail until ACP lands. Remove executor.leash or wait for Phase B."
            )

        bin_path = self._resolve_bin()
        has_auth = (home / "auth.json").exists()
        has_key = any(os.environ.get(k) for k in _API_KEY_ENVS)
        if bin_path is None:
            logger.warning(
                f"[{self.profile.name}] `grok` CLI not found on PATH "
                f"(GROK_BIN={os.environ.get('GROK_BIN')!r}). Install Grok Build "
                "or set GROK_BIN. Published images install the CLI at build time."
            )
        if not has_auth and not has_key:
            logger.warning(
                f"[{self.profile.name}] no auth.json in {home} and no "
                f"{'/'.join(_API_KEY_ENVS)} — executor turns will fail auth. "
                "Run `miragen grok-login --grok-home <shared volume>` once "
                "(subscription) or set XAI_API_KEY. Agent containers never "
                "log in. See docs/design/subscription-homes.md."
            )

    def _resolve_bin(self) -> str | None:
        if self._grok_bin:
            return self._grok_bin
        env_bin = os.environ.get("GROK_BIN")
        if env_bin and Path(env_bin).exists():
            return env_bin
        return shutil.which("grok")

    # ── Turn streaming ─────────────────────────────────────────────────────

    async def _stream_turn(
        self,
        prompt: str,
        *,
        run_id: str,
        thread_id: str | None,
        workspace: Path,
        first_turn: bool,
    ) -> AsyncIterator[dict[str, Any]]:
        if self.leash_enabled:
            yield {
                "type": "turn.failed",
                "error": {
                    "message": (
                        "grok-build Phase A does not support host leash "
                        "(no pre-tool approval on headless streaming-json). "
                        "Remove executor.leash or wait for ACP Phase B."
                    ),
                },
            }
            return

        options = self._options(workspace, thread_id=thread_id, first_turn=first_turn)
        # Emit resume handle before the process streams so a timeout still
        # recovers it even if no `end` event arrives.
        yield {"type": "thread.started", "thread_id": options["session_id"]}

        session = self._session_factory(
            prompt,
            thread_id=options["session_id"] if not first_turn and thread_id else None,
            first_turn=first_turn,
            options=options,
        )
        text_parts: list[str] = []
        saw_terminal = False
        async for raw in session:
            if isinstance(raw, dict) and raw.get("type") in {
                "thread.started", "turn.completed", "turn.failed", "item.completed",
            }:
                # Already-normalized payload (test seam).
                if raw.get("type") == "thread.started":
                    continue  # already emitted above
                yield raw
                if raw.get("type") in ("turn.completed", "turn.failed"):
                    saw_terminal = True
                continue

            for payload in _normalize_event(raw if isinstance(raw, dict) else {}):
                kind = payload.get("type")
                if kind == "item.completed":
                    item = payload.get("item") or {}
                    if item.get("type") == "agent_message" and item.get("text"):
                        # Accumulate streaming text; emit one final message later.
                        text_parts.append(item["text"])
                        continue
                if kind in ("turn.completed", "turn.failed"):
                    saw_terminal = True
                yield payload

        if text_parts:
            yield {
                "type": "item.completed",
                "item": {"type": "agent_message", "text": "".join(text_parts)},
            }
        if not saw_terminal:
            # Process exited without end/error — treat as success if we got text,
            # else a soft failure is still better than hanging as 'running'.
            yield {"type": "turn.completed", "usage": {}}

    def _options(
        self, workspace: Path, *, thread_id: str | None, first_turn: bool
    ) -> dict[str, Any]:
        # First turn: mint UUID for -s. Resume: reuse thread_id with -r.
        if first_turn or not thread_id:
            session_id = str(uuid.uuid4())
            resume = False
        else:
            session_id = thread_id
            resume = True

        yolo = self.spec.approval_policy == "never"
        return {
            "cwd": str(workspace),
            "session_id": session_id,
            "resume": resume,
            "always_approve": yolo,
            "model": self.spec.model,
            "reasoning_effort": self.spec.reasoning_effort,
            "web_search": self.spec.web_search,
            "grok_home": self.spec.grok_home,
        }

    async def _default_session(
        self,
        prompt: str,
        *,
        thread_id: str | None,
        first_turn: bool,
        options: dict[str, Any],
    ) -> AsyncIterator[Any]:
        grok = self._resolve_bin()
        if not grok:
            yield {
                "type": "error",
                "message": "grok CLI not found on PATH (set GROK_BIN or install Grok Build)",
            }
            return

        argv = _build_argv(grok, prompt, options)
        env = os.environ.copy()
        env["GROK_HOME"] = str(options["grok_home"])

        proc = await asyncio.create_subprocess_exec(
            *argv,
            cwd=options["cwd"],
            stdin=asyncio.subprocess.DEVNULL,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
            env=env,
            start_new_session=True,
        )

        lines: list[str] = []
        try:
            assert proc.stdout is not None
            while True:
                raw = await proc.stdout.readline()
                if not raw:
                    break
                text = raw.decode(errors="replace").rstrip("\n")
                if not text:
                    continue
                lines.append(text)
                try:
                    event = json.loads(text)
                except ValueError:
                    # Non-JSON noise (warnings) — surface as stdout item later via tail.
                    continue
                if isinstance(event, dict):
                    yield event
            returncode = await proc.wait()
        except asyncio.CancelledError:
            with contextlib.suppress(ProcessLookupError, PermissionError):
                os.killpg(proc.pid, signal.SIGKILL)
            with contextlib.suppress(Exception):
                await asyncio.wait_for(proc.wait(), timeout=5)
            raise

        if returncode != 0:
            # Prefer a structured error event if the stream already carried one;
            # otherwise synthesize from exit code + tail.
            yield {
                "type": "error",
                "message": f"grok exited with code {returncode}",
                "tail": lines[-_ERROR_TAIL_LINES:],
            }


def _build_argv(grok: str, prompt: str, options: dict[str, Any]) -> list[str]:
    argv = [
        grok,
        "--no-auto-update",
        "-p", prompt,
        "--cwd", options["cwd"],
        "--output-format", "streaming-json",
    ]
    if options.get("always_approve"):
        argv.append("--always-approve")
    if options.get("resume"):
        argv.extend(["-r", options["session_id"]])
    else:
        argv.extend(["-s", options["session_id"]])
    if options.get("model"):
        argv.extend(["-m", options["model"]])
    if options.get("reasoning_effort"):
        argv.extend(["--reasoning-effort", options["reasoning_effort"]])
    if not options.get("web_search"):
        argv.append("--disable-web-search")
    return argv


def _normalize_event(event: dict[str, Any]) -> list[dict[str, Any]]:
    """Map one Grok streaming-json / json event onto base-tier payloads.

    Documented types: text, thought, end, error. Unknown types are ignored.
    """
    etype = event.get("type")

    if etype == "text":
        data = event.get("data") or ""
        if not data:
            return []
        return [{
            "type": "item.completed",
            "item": {"type": "agent_message", "text": data},
        }]

    if etype == "thought":
        data = event.get("data") or ""
        if not data:
            return []
        return [{
            "type": "item.completed",
            "item": {"type": "reasoning", "text": data},
        }]

    if etype == "end":
        # sessionId on end can refine the resume handle if we didn't mint -s,
        # but Phase A always mints; still fold usage.
        usage = _usage_from_end(event)
        payloads: list[dict[str, Any]] = []
        sid = event.get("sessionId")
        if sid:
            payloads.append({"type": "thread.started", "thread_id": sid})
        payloads.append({"type": "turn.completed", "usage": usage})
        return payloads

    if etype == "error":
        return [{
            "type": "turn.failed",
            "error": {
                "message": event.get("message") or "grok reported an error",
                "tail": event.get("tail"),
            },
        }]

    # json (non-streaming) shape without type — rare if we always request streaming-json
    if etype is None and ("text" in event or "sessionId" in event):
        payloads = []
        if event.get("sessionId"):
            payloads.append({"type": "thread.started", "thread_id": event["sessionId"]})
        if event.get("text"):
            payloads.append({
                "type": "item.completed",
                "item": {"type": "agent_message", "text": event["text"]},
            })
        payloads.append({"type": "turn.completed", "usage": _usage_from_end(event)})
        return payloads

    return []


def _usage_from_end(event: dict[str, Any]) -> dict[str, Any]:
    raw = event.get("usage")
    if not isinstance(raw, dict):
        return {}
    usage: dict[str, Any] = {
        "input_tokens": raw.get("input_tokens"),
        "output_tokens": raw.get("output_tokens"),
    }
    cached = raw.get("cache_read_input_tokens")
    if cached is not None:
        usage["cached_input_tokens"] = cached
    return usage
