"""Grok Build adapter — headless + ACP via the MIT `grok-build-client` package.

Self-harnessed coding agent via the `grok` CLI. Transport is pluggable:

  - headless (default): one `grok -p` process per turn, streaming-json.
  - acp: long-lived `grok agent stdio` (JSON-RPC). Required for host leash.

Auth (subscription-first, see docs/design/subscription-homes.md):
  - Primary: SuperGrok / X Premium+ OAuth under GROK_HOME (profile grok_home),
    populated once by `miragen grok-login` (`grok login --device-auth`).
  - Fallback: XAI_API_KEY (metered).
Agent containers never log in; they mount the shared home.

Session / resume:
  - Headless: mint UUID (`-s`) / resume (`-r`).
  - ACP: session/new or session/load; session id is the resume handle.
"""

from __future__ import annotations

import logging
import os
import uuid
from pathlib import Path
from typing import Any, AsyncIterator, Callable

from miragen.executor.base import ExecutorBackend
from miragen.executor.grok_hermetic import (
    hermetic_home_dir,
    hermetic_owner,
    refresh_hermetic_files,
    release_hermetic_home,
    write_hermetic_home,
)
from miragen.executor.leash import GateOperation
from miragen.models import AgentProfile

logger = logging.getLogger("miragen.executor")

_API_KEY_ENVS = ("XAI_API_KEY", "GROK_CODE_XAI_API_KEY")
# Non-GROK_* env that points grok's compat scanners at foreign harness state.
_HERMETIC_DROP_ENVS = frozenset({"CLAUDE_CONFIG_DIR", "CODEX_HOME", "CURSOR_CONFIG_DIR"})


class GrokBuildExecutor(ExecutorBackend):
    """Runs jobs through Grok Build (headless or ACP).

    `session_factory` is the test seam: `(prompt, *, thread_id, first_turn,
    options) -> AsyncIterator` of client events or already-normalized base
    payloads.
    """

    def __init__(
        self,
        profile: AgentProfile,
        *,
        runs_root: Path = Path("/agent/runs"),
        session_factory: Callable[..., AsyncIterator[Any]] | None = None,
        grok_bin: str | None = None,
    ):
        super().__init__(profile, runs_root=runs_root)
        self._session_factory = session_factory or self._default_session
        self._grok_bin = grok_bin

    @property
    def transport(self) -> str:
        return self.spec.grok_transport or "headless"

    # ── Startup ────────────────────────────────────────────────────────────

    def prepare(self) -> None:
        home = Path(self.spec.grok_home)
        home.mkdir(parents=True, exist_ok=True)
        os.environ["GROK_HOME"] = str(home)

        if self.spec.grok_hermetic:
            write_hermetic_home(home, self.profile.name, self.spec)
            logger.info(
                f"[{self.profile.name}] hermetic GROK_HOME written: {home} "
                f"(MCP servers: {[s.name for s in self.spec.mcp_servers or []]})"
            )
        else:
            owner = hermetic_owner(home)
            if owner == self.profile.name:
                release_hermetic_home(home)
                logger.info(
                    f"[{self.profile.name}] grok_hermetic turned off: removed the "
                    f"miragen-owned hermetic config from {home}"
                )
            elif owner is not None:
                logger.warning(
                    f"[{self.profile.name}] {home} is the hermetic home of agent "
                    f"{owner!r}: its requirements.toml pins (compat off, MCP URL "
                    "allowlist, managed hooks only) also clamp this agent. Give "
                    "each hermetic agent its own grok_home."
                )
            config_path = home / "config.toml"
            if not config_path.exists():
                config_path.write_text(
                    "# Generated by miragen at startup — edit the agent profile instead.\n"
                    f"# agent: {self.profile.name}\n"
                    "[cli]\n"
                    "auto_update = false\n"
                )

        if self.leash_enabled and self.transport == "headless":
            logger.warning(
                f"[{self.profile.name}] host leash requires grok_transport: acp; "
                "headless turns will fail. Set executor.grok_transport: acp."
            )

        from grok_build_client import resolve_grok_bin

        bin_path = resolve_grok_bin(self._grok_bin)
        has_auth = (home / "auth.json").exists()
        has_key = self.spec.grok_auth != "subscription" and any(
            os.environ.get(k) for k in _API_KEY_ENVS
        )
        if self.spec.grok_auth == "subscription" and not has_auth:
            logger.warning(
                f"[{self.profile.name}] grok_auth: subscription but no auth.json in "
                f"{home} — {'/'.join(_API_KEY_ENVS)} are withheld from grok, so "
                "turns will fail auth until `miragen grok-login --grok-home "
                f"{home}` is run."
            )
        if bin_path is None:
            logger.warning(
                f"[{self.profile.name}] `grok` CLI not found on PATH "
                f"(GROK_BIN={os.environ.get('GROK_BIN')!r}). Install Grok Build "
                "or set GROK_BIN. Published images install the CLI at build time."
            )
        if not has_auth and not has_key and self.spec.grok_auth != "subscription":
            logger.warning(
                f"[{self.profile.name}] no auth.json in {home} and no "
                f"{'/'.join(_API_KEY_ENVS)} — executor turns will fail auth. "
                "Run `miragen grok-login --grok-home <shared volume>` once "
                "(subscription) or set XAI_API_KEY. Agent containers never "
                "log in. See docs/design/subscription-homes.md."
            )

    # ── Turn streaming ─────────────────────────────────────────────────────

    async def _stream_turn(
        self,
        prompt: str,
        *,
        run_id: str,
        thread_id: str | None,
        workspace: Path,
        first_turn: bool,
        mcp_secret_env: dict[str, str] | None = None,
    ) -> AsyncIterator[dict[str, Any]]:
        transport = self.transport
        if self.leash_enabled and transport == "headless":
            yield {
                "type": "turn.failed",
                "error": {
                    "message": (
                        "grok-build host leash requires grok_transport: acp "
                        "(headless has no pre-tool approval seam)"
                    ),
                },
            }
            return

        options = self._options(
            workspace,
            thread_id=thread_id,
            first_turn=first_turn,
            transport=transport,
            mcp_secret_env=mcp_secret_env,
        )
        yield {"type": "thread.started", "thread_id": options["session_id"]}

        session = self._session_factory(
            prompt,
            thread_id=options["session_id"] if options.get("resume") else None,
            first_turn=first_turn,
            options=options,
        )
        text_parts: list[str] = []
        saw_terminal = False
        async for raw in session:
            if isinstance(raw, dict) and raw.get("type") in {
                "thread.started", "turn.completed", "turn.failed", "item.completed",
            }:
                # Already-normalized base payloads (test seam).
                yield raw
                if raw.get("type") in ("turn.completed", "turn.failed"):
                    saw_terminal = True
                continue

            for payload in _to_base_payload(raw if isinstance(raw, dict) else {}):
                kind = payload.get("type")
                if kind == "item.completed":
                    item = payload.get("item") or {}
                    if item.get("type") == "agent_message" and item.get("text"):
                        text_parts.append(item["text"])
                        continue
                if kind in ("turn.completed", "turn.failed"):
                    saw_terminal = True
                # thread.started updates (e.g. real ACP session id) must pass
                # through so the base can replace a provisional handle.
                yield payload

        if text_parts:
            yield {
                "type": "item.completed",
                "item": {"type": "agent_message", "text": "".join(text_parts)},
            }
        if not saw_terminal:
            yield {
                "type": "turn.failed",
                "error": {
                    "message": "grok exited without a terminal event (end/error)",
                },
            }

    def _options(
        self,
        workspace: Path,
        *,
        thread_id: str | None,
        first_turn: bool,
        transport: str,
        mcp_secret_env: dict[str, str] | None = None,
    ) -> dict[str, Any]:
        if first_turn or not thread_id:
            session_id = str(uuid.uuid4()) if transport == "headless" else (thread_id or "")
            resume = False
        else:
            session_id = thread_id
            resume = True

        # ACP mints session ids server-side on session/new; placeholder until then.
        if transport == "acp" and not resume:
            session_id = session_id or "pending"

        yolo = self.spec.approval_policy == "never" and not self.leash_enabled
        return {
            "transport": transport,
            "cwd": str(workspace),
            "session_id": session_id,
            "resume": resume,
            "always_approve": yolo,
            "model": self.spec.model,
            "reasoning_effort": self.spec.reasoning_effort,
            "web_search": self.spec.web_search,
            "grok_home": self.spec.grok_home,
            "mcp_servers": (
                self._mcp_configs(mcp_secret_env) if transport == "acp" else None
            ),
            "leash": self.leash_enabled,
            "tools": self.spec.grok_tools,
            "disallowed_tools": self.spec.grok_disallowed_tools,
            "permission_mode": self.spec.grok_permission_mode,
            "allow": list(self.spec.grok_allow),
            "deny": list(self.spec.grok_deny),
            "max_turns": self.spec.grok_max_turns,
            "env": self._grok_env(mcp_secret_env, transport=transport),
        }

    def _grok_env(
        self,
        mcp_secret_env: dict[str, str] | None = None,
        *,
        transport: str,
    ) -> dict[str, str]:
        """The grok subprocess environment, built per turn (never by
        mutating os.environ: this executor is shared by concurrent runs).

        - grok_auth 'subscription': XAI_API_KEY / GROK_CODE_XAI_API_KEY are
          removed, so a lapsed login fails instead of silently metering.
        - grok_hermetic (headless): HOME is the empty miragen-owned
          `<grok_home>/hermetic-home` (no ~/.claude plugins or ~/.claude.json,
          no ~/.agents skills, no ~/.cursor), every GROK_* except GROK_HOME is
          dropped (they outrank config.toml), and each declared MCP server's
          `bearer_token_env` is set from this turn's secrets so grok's
          `${VAR}` header expansion resolves.
        """
        env = dict(os.environ)
        env["GROK_HOME"] = str(self.spec.grok_home)
        if self.spec.grok_auth == "subscription":
            for key in _API_KEY_ENVS:
                env.pop(key, None)
        if self.spec.grok_hermetic and transport == "headless":
            for key in list(env):
                if (key.startswith("GROK_") and key != "GROK_HOME") or key in _HERMETIC_DROP_ENVS:
                    del env[key]
            hermetic_home = hermetic_home_dir(Path(self.spec.grok_home))
            env["HOME"] = str(hermetic_home)
            env["XDG_CONFIG_HOME"] = str(hermetic_home / ".config")
            env["XDG_DATA_HOME"] = str(hermetic_home / ".local" / "share")
            env["XDG_CACHE_HOME"] = str(hermetic_home / ".cache")
            for server in self.spec.mcp_servers or []:
                name = server.bearer_token_env
                if not name:
                    continue
                value = (mcp_secret_env or {}).get(name) or os.environ.get(name)
                if value:
                    env[name] = value
                else:
                    env.pop(name, None)
                    logger.warning(
                        f"[{self.profile.name}] MCP server {server.name!r}: "
                        f"{name} is unset for this turn — grok will send an "
                        "empty bearer token"
                    )
        return env

    def _mcp_configs(
        self,
        mcp_secret_env: dict[str, str] | None = None,
    ) -> list[dict[str, Any]] | None:
        if not self.spec.mcp_servers:
            return None
        configs: list[dict[str, Any]] = []
        for server in self.spec.mcp_servers:
            cfg: dict[str, Any] = {"name": server.name, "type": "http", "url": server.url}
            if server.bearer_token_env:
                token = (mcp_secret_env or {}).get(
                    server.bearer_token_env
                ) or os.environ.get(server.bearer_token_env)
                if token:
                    cfg["headers"] = {"Authorization": f"Bearer {token}"}
            configs.append(cfg)
        return configs

    async def _default_session(
        self,
        prompt: str,
        *,
        thread_id: str | None,
        first_turn: bool,
        options: dict[str, Any],
    ) -> AsyncIterator[Any]:
        transport = options.get("transport") or "headless"
        if transport == "acp":
            async for event in self._acp_session(prompt, options):
                yield event
        else:
            async for event in self._headless_session(prompt, options):
                yield event

    async def _headless_session(self, prompt: str, options: dict[str, Any]) -> AsyncIterator[Any]:
        from grok_build_client import HeadlessSession

        if self.spec.grok_hermetic:
            refresh_hermetic_files(Path(self.spec.grok_home), self.profile.name, self.spec)

        session = HeadlessSession(
            prompt=prompt,
            cwd=options["cwd"],
            session_id=options["session_id"],
            resume=bool(options.get("resume")),
            always_approve=bool(options.get("always_approve")),
            model=options.get("model"),
            reasoning_effort=options.get("reasoning_effort"),
            web_search=bool(options.get("web_search")),
            grok_home=options.get("grok_home"),
            grok_bin=self._grok_bin,
            env=options.get("env"),
            tools=options.get("tools"),
            disallowed_tools=options.get("disallowed_tools"),
            permission_mode=options.get("permission_mode"),
            allow=list(options.get("allow") or []),
            deny=list(options.get("deny") or []),
            max_turns=options.get("max_turns"),
        )
        async for event in session.run():
            yield event

    async def _acp_session(self, prompt: str, options: dict[str, Any]) -> AsyncIterator[Any]:
        from grok_build_client import AcpSession

        handler = self._permission_handler if options.get("leash") else None
        async with AcpSession(
            grok_bin=self._grok_bin,
            grok_home=options.get("grok_home"),
            always_approve=bool(options.get("always_approve")),
            model=options.get("model"),
            permission_handler=handler,
            env=options.get("env"),
        ) as acp:
            if options.get("resume") and options.get("session_id") not in (None, "", "pending"):
                session_id = await acp.session_load(options["session_id"], cwd=options["cwd"])
            else:
                session_id = await acp.session_new(
                    options["cwd"],
                    mcp_servers=options.get("mcp_servers"),
                    yolo=bool(options.get("always_approve")),
                )
            # Real ACP session id (overrides provisional handle from options).
            yield {"type": "session", "sessionId": session_id}

            async for event in acp.prompt(session_id, prompt):
                if event.get("type") == "end" and not event.get("sessionId"):
                    event = {**event, "sessionId": session_id}
                yield event

    def _permission_handler(self, params: dict[str, Any]) -> str:
        """ACP permission callback → host leash."""
        op = _gate_operation_from_acp(params)
        if op is None:
            return "allow"
        decision = self.gate_decide(op)
        return "allow" if decision.allow else "deny"


def _gate_operation_from_acp(params: dict[str, Any]) -> GateOperation | None:
    """Best-effort map of ACP permission params to a GateOperation."""
    # Shapes vary by agent build; probe common fields.
    tool_call = params.get("toolCall") or params.get("tool_call") or params
    if not isinstance(tool_call, dict):
        tool_call = params
    title = (tool_call.get("title") or tool_call.get("kind") or tool_call.get("toolName") or "")
    title_l = str(title).lower()
    raw_input = tool_call.get("rawInput") or tool_call.get("input") or {}
    if not isinstance(raw_input, dict):
        raw_input = {}
    command = raw_input.get("command") or raw_input.get("cmd") or ""
    summary = (command or title or str(params))[:120]

    if "bash" in title_l or "shell" in title_l or "terminal" in title_l or command:
        return GateOperation(op_class="command", command=str(command), summary=summary)
    if any(k in title_l for k in ("edit", "write", "create", "file")):
        return GateOperation(op_class="write", summary=summary)
    if any(k in title_l for k in ("fetch", "web", "http", "network")):
        return GateOperation(op_class="network", summary=summary)
    return None


def _to_base_payload(event: dict[str, Any]) -> list[dict[str, Any]]:
    """Map grok-build-client events onto miragen base executor payloads."""
    etype = event.get("type")

    if etype == "session":
        sid = event.get("sessionId")
        return [{"type": "thread.started", "thread_id": sid}] if sid else []

    if etype == "text":
        data = event.get("data") or ""
        if not data:
            return []
        return [{"type": "item.completed", "item": {"type": "agent_message", "text": data}}]

    if etype == "thought":
        data = event.get("data") or ""
        if not data:
            return []
        return [{"type": "item.completed", "item": {"type": "reasoning", "text": data}}]

    if etype == "tool_call":
        return [{
            "type": "item.completed",
            "item": {"type": "tool_use", "name": event.get("name"), "status": event.get("status")},
        }]

    if etype == "end":
        usage = _usage_from_client(event.get("usage") or {})
        payloads: list[dict[str, Any]] = []
        if event.get("sessionId"):
            payloads.append({"type": "thread.started", "thread_id": event["sessionId"]})
        payloads.append({"type": "turn.completed", "usage": usage})
        return payloads

    if etype == "error":
        return [{
            "type": "turn.failed",
            "error": {"message": event.get("message") or "grok reported an error"},
        }]

    # Raw headless CLI shapes (type/data) that bypassed client normalize
    if etype is None and ("text" in event or "sessionId" in event):
        from grok_build_client import normalize_headless_event

        out: list[dict[str, Any]] = []
        for norm in normalize_headless_event(event):
            out.extend(_to_base_payload(norm))
        return out

    return []


def _usage_from_client(raw: dict[str, Any]) -> dict[str, Any]:
    if not raw:
        return {}
    # Headless snake_case or ACP camelCase
    usage: dict[str, Any] = {
        "input_tokens": raw.get("input_tokens", raw.get("inputTokens")),
        "output_tokens": raw.get("output_tokens", raw.get("outputTokens")),
    }
    cached = raw.get("cache_read_input_tokens", raw.get("cacheReadInputTokens"))
    if cached is not None:
        usage["cached_input_tokens"] = cached
    return usage


# Back-compat for tests that imported private helpers from the Phase A module.
def _build_argv(grok: str, prompt: str, options: dict[str, Any]) -> list[str]:
    from grok_build_client import build_headless_argv

    return build_headless_argv(
        grok,
        prompt,
        cwd=options["cwd"],
        session_id=options.get("session_id"),
        resume=bool(options.get("resume")),
        always_approve=bool(options.get("always_approve", True)),
        model=options.get("model"),
        reasoning_effort=options.get("reasoning_effort"),
        web_search=bool(options.get("web_search")),
    )


def _normalize_event(event: dict[str, Any]) -> list[dict[str, Any]]:
    """Phase A name — normalize headless raw events to base payloads."""
    from grok_build_client import normalize_headless_event

    out: list[dict[str, Any]] = []
    for norm in normalize_headless_event(event):
        out.extend(_to_base_payload(norm))
    return out
