"""Executor backend tier — self-harnessed executors (Codex first).

Contract: workspace-in / diff-and-events-out. The executor owns its own agent
loop; miragen owes the layers above a sufficient event stream (turn events,
tool/item events, exit reason) and a diff harvested EXACTLY ONCE on terminal
success. Tool-level failures inside the loop are the agent's problem and are
not modeled here.

State machine (design record: miradb #293):

    running -> succeeded            (diff harvested)
            -> suspended  (budget)  RESUMABLE
            -> failed     (crash)   RESUMABLE
            -> abandoned            (human gave up; only human-terminal state)

Workspace lifetime != container lifetime: the workspace is a persistent
volume keyed to the agent-run, alongside the executor thread_id on the run
record. The container is disposable; resume re-opens the thread bound to the
run and reuses its workspace.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, AsyncIterator, Callable

from miragen.models import AgentProfile, ExecutorSpec, RunUsage, sum_usage

logger = logging.getLogger("miragen.executor")

_DIFF_NAME = "diff.patch"
_EVENTS_SUFFIX = ".events.jsonl"
_BASELINE_TAG = "miragen-baseline"


class ExecutorResult:
    """Terminal outcome of one executor turn bound to an agent-run."""

    def __init__(
        self,
        *,
        status: str,
        exit_reason: str | None = None,
        thread_id: str | None = None,
        output: str | None = None,
        error: str | None = None,
        usage: RunUsage | None = None,
        diff_path: str | None = None,
    ):
        self.status = status
        self.exit_reason = exit_reason
        self.thread_id = thread_id
        self.output = output
        self.error = error
        self.usage = usage
        self.diff_path = diff_path


class CodexExecutor:
    """Runs jobs through the official openai-codex-sdk.

    The SDK wraps the bundled `codex` CLI (`codex exec --experimental-json`,
    `... resume <thread_id>`) and yields typed Pydantic events — verified
    against openai-codex-sdk 0.1.11. `thread_factory` exists for tests: it
    receives (codex, thread_id | None, thread_options) and returns a Thread-
    compatible object with `.id` and `.run_streamed(prompt)`.
    """

    def __init__(
        self,
        profile: AgentProfile,
        *,
        runs_root: Path = Path("/agent/runs"),
        thread_factory: Callable[..., Any] | None = None,
    ):
        assert profile.executor is not None, "CodexExecutor requires an executor-tier profile"
        self.profile = profile
        self.spec: ExecutorSpec = profile.executor
        self.runs_root = Path(runs_root)
        self._thread_factory = thread_factory or self._sdk_thread

    # ── Startup ────────────────────────────────────────────────────────────

    def prepare(self) -> None:
        """Write the executor's config (MCP servers, trust settings) into
        CODEX_HOME. Idempotent; called once at container startup.

        auth.json is NOT written here — it must be volume-mounted into
        CODEX_HOME by the deployment (per-agent Origo/Codex credentials are
        spawn-time secrets, never profile content).
        """
        codex_home = Path(self.spec.codex_home)
        codex_home.mkdir(parents=True, exist_ok=True)
        os.environ.setdefault("CODEX_HOME", str(codex_home))

        config_path = codex_home / "config.toml"
        config_path.write_text(self._render_config())
        logger.info(f"[{self.profile.name}] executor config written: {config_path}")

        if not (codex_home / "auth.json").exists() and not os.environ.get("CODEX_API_KEY"):
            logger.warning(
                f"[{self.profile.name}] no auth.json in {codex_home} and CODEX_API_KEY unset — "
                "executor spawns will fail auth. Mount auth.json into CODEX_HOME."
            )

    def _render_config(self) -> str:
        lines = [
            "# Generated by miragen at startup — do not edit; edit the agent profile instead.",
            f'# agent: {self.profile.name}',
        ]
        for server in self.spec.mcp_servers or []:
            lines += [
                "",
                f"[mcp_servers.{server.name}]",
                f'url = "{server.url}"',
            ]
            if server.bearer_token_env:
                # Reference by NAME: the per-agent credential is injected into the
                # container environment at spawn, not stored in config.
                lines.append(f'bearer_token_env_var = "{server.bearer_token_env}"')
        return "\n".join(lines) + "\n"

    # ── Job execution ──────────────────────────────────────────────────────

    async def run_job(
        self,
        prompt: str,
        run_id: str,
        *,
        thread_id: str | None = None,
        workspace: str | None = None,
        first_turn: bool = True,
        prior_usage: RunUsage | None = None,
    ) -> ExecutorResult:
        """Execute one turn of a job bound to an agent-run.

        First turn: fresh workspace + fresh thread; `instructions` are
        prepended. Resume: existing workspace + `resume_thread(thread_id)`.
        `prior_usage` is the run's accumulated usage from earlier turns —
        needed so a per-run budget check on resume sees the true total, not
        just this turn's usage.
        """
        ws = Path(workspace) if workspace else Path(self.spec.workspace_root) / run_id

        if first_turn and self.spec.instructions:
            prompt = f"{self.spec.instructions}\n\n{prompt}"

        events_path = self._events_path(run_id)
        events_path.parent.mkdir(parents=True, exist_ok=True)

        usage: RunUsage | None = None
        output: str | None = None
        error: str | None = None
        observed_thread_id: str | None = thread_id
        turn_failed = False

        try:
            # Inside the try: a bad workspace_root, missing git, or a
            # permission error here must still produce a 'failed' result
            # (and thus a RunStore.finish() call) rather than an unhandled
            # exception that leaves the run record stuck at 'running'.
            self._prepare_workspace(ws)
            thread = self._thread_factory(
                thread_id=thread_id,
                options=self._thread_options(ws),
            )
            streamed = await thread.run_streamed(prompt)
            with events_path.open("a") as sink:
                async for event in self._iter_events(streamed):
                    payload = self._event_payload(event)
                    sink.write(json.dumps(payload, default=str) + "\n")

                    kind = payload.get("type")
                    if kind == "thread.started":
                        observed_thread_id = payload.get("thread_id") or observed_thread_id
                    elif kind == "turn.completed":
                        usage = _usage_from_payload(payload.get("usage"))
                    elif kind == "turn.failed":
                        turn_failed = True
                        error = json.dumps(payload.get("error")) if payload.get("error") else "turn failed"
                    elif kind == "item.completed":
                        item = payload.get("item") or {}
                        if item.get("type") in ("agent_message", "agent-message"):
                            output = item.get("text") or output
            observed_thread_id = observed_thread_id or getattr(thread, "id", None)
        except Exception as e:
            # Crash / API error: resumable. Partial workspace changes are
            # neither harvested nor discarded — they are resume state.
            logger.error(f"[{self.profile.name}] executor crashed: {e}", exc_info=True)
            return ExecutorResult(
                status="failed",
                exit_reason="crash",
                thread_id=observed_thread_id,
                error=str(e),
                usage=usage,
            )

        if turn_failed:
            return ExecutorResult(
                status="failed",
                exit_reason="crash",
                thread_id=observed_thread_id,
                error=error,
                usage=usage,
            )

        if self._budget_exhausted(sum_usage(prior_usage, usage)):
            # Turn completed but blew the per-run budget: suspend, keep the
            # partial diff as resume state, do not harvest. Checked against
            # the run's cumulative usage (prior turns + this one) — a resumed
            # run must not be able to sneak back under a per-run cap just
            # because a single resumed turn's own usage looks small.
            return ExecutorResult(
                status="suspended",
                exit_reason="budget",
                thread_id=observed_thread_id,
                output=output,
                usage=usage,
            )

        diff_path = await self._harvest_diff(ws)
        return ExecutorResult(
            status="succeeded",
            thread_id=observed_thread_id,
            output=output,
            usage=usage,
            diff_path=diff_path,
        )

    # ── Pieces ─────────────────────────────────────────────────────────────

    def _sdk_thread(self, *, thread_id: str | None, options: Any):
        from openai_codex_sdk import Codex

        codex = Codex()
        if thread_id:
            return codex.resume_thread(thread_id, options)
        return codex.start_thread(options)

    def _thread_options(self, workspace: Path) -> Any:
        try:
            from openai_codex_sdk.types import ThreadOptions
        except ImportError:  # tests with a stub factory never reach the SDK
            return {
                "working_directory": str(workspace),
                "sandbox_mode": self.spec.sandbox_mode,
                "approval_policy": self.spec.approval_policy,
            }
        return ThreadOptions(
            model=self.spec.model,
            sandbox_mode=self.spec.sandbox_mode,
            working_directory=str(workspace),
            skip_git_repo_check=True,  # miragen initializes the repo itself
            model_reasoning_effort=self.spec.reasoning_effort,
            network_access_enabled=self.spec.network_access,
            web_search_enabled=self.spec.web_search,
            # Explicit ALWAYS: an unattended executor waiting on interactive
            # approval stalls the job (operational gotcha, miradb #293).
            approval_policy=self.spec.approval_policy,
        )

    @staticmethod
    async def _iter_events(streamed: Any) -> AsyncIterator[Any]:
        events = getattr(streamed, "events", streamed)
        if hasattr(events, "__aiter__"):
            async for event in events:
                yield event
        else:  # pragma: no cover — sync iterable stubs
            for event in events:
                yield event
                await asyncio.sleep(0)

    @staticmethod
    def _event_payload(event: Any) -> dict[str, Any]:
        if isinstance(event, dict):
            payload = dict(event)
        elif hasattr(event, "model_dump"):
            payload = event.model_dump(by_alias=False)
        else:
            payload = {"type": "unknown", "repr": repr(event)}
        payload.setdefault("ts", datetime.now(timezone.utc).isoformat())
        return payload

    def _events_path(self, run_id: str) -> Path:
        return self.runs_root / f"{run_id}{_EVENTS_SUFFIX}"

    def read_events(self, run_id: str, limit: int = 200) -> list[dict[str, Any]]:
        path = self._events_path(run_id)
        if not path.exists():
            return []
        events = []
        with path.open() as f:
            for line in f:
                line = line.strip()
                if line:
                    try:
                        events.append(json.loads(line))
                    except ValueError:
                        continue
        return events[-limit:]

    def _prepare_workspace(self, ws: Path) -> None:
        ws.mkdir(parents=True, exist_ok=True)
        if not (ws / ".git").exists():
            # The diff IS the deliverable; a git baseline makes harvest exact.
            # Tagged (not just left as a loose commit) so harvest can diff
            # against it even after the executor makes its own commits —
            # the tag lives in .git, so the executor's own `git add -A` /
            # commits never touch or shadow it.
            _git(ws, "init", "-q")
            _git(ws, "add", "-A")
            _git(ws, "-c", "user.email=miragen@local", "-c", "user.name=miragen",
                 "commit", "-q", "--allow-empty", "-m", "miragen: workspace baseline")
            _git(ws, "tag", "-f", _BASELINE_TAG)

    async def _harvest_diff(self, ws: Path) -> str:
        """git-diff harvest, exactly once, on terminal success (§293 decision 3).

        Diffs against the baseline tag, not HEAD: if the executor committed
        mid-turn, HEAD has moved past the baseline, and `git diff --cached`
        with no revision arg would only show the *uncommitted* remainder,
        silently dropping everything the executor already committed.
        """
        _git(ws, "add", "-A")  # stage everything so new files appear in the diff
        diff = _git(ws, "diff", "--cached", "--binary", _BASELINE_TAG)
        marker_dir = ws / ".miragen"
        marker_dir.mkdir(exist_ok=True)
        diff_path = marker_dir / _DIFF_NAME
        diff_path.write_text(diff)
        return str(diff_path)

    def _budget_exhausted(self, usage: RunUsage | None) -> bool:
        limits = self.profile.limits
        if limits is None or limits.tokens_per_run is None or usage is None:
            return False
        total = (usage.input_tokens or 0) + (usage.output_tokens or 0)
        return total > limits.tokens_per_run


def _usage_from_payload(raw: Any) -> RunUsage | None:
    if not isinstance(raw, dict):
        return None
    return RunUsage(
        requests=1,
        input_tokens=raw.get("input_tokens"),
        output_tokens=raw.get("output_tokens"),
    )


def _git(ws: Path, *args: str) -> str:
    import subprocess

    result = subprocess.run(
        ["git", "-C", str(ws), *args],
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout
